### PR TITLE
Add Spago build using package-sets/psc-0.12.5-20190508. #97

### PR DESCRIPTION
**Pull request by epost**

### CODE REVIEW

**Comment by nkly** [comment]
Hi! Thanks for the contribution. Do you think it makes sense to add an additional step in Travis setup to test that the project builds with Spago?

**Comment by i-am-the-slime** [comment]
Yes

**Comment by srghma** [comment]
> additional step in Travis setup

it's better to replace travis with github actions - all projects in purescript org are using it IIRC

**Comment by srghma** [comment]
will add github actions later https://github.com/purescript-express/purescript-express/issues/108

**Pull request merged**
